all: temperature-humidity heart-oxygen pressure main

temperature-humidity:
	chmod -v +x temperature-humidity/temperature_humidity.py

heart-oxygen:
	chmod -v +x heart-oxygen/data_processing.py heart-oxygen/script.sh

pressure:
	chmod -v +x pressure/pressure.py

main:
	chmod -v +x led.py email.sh script.sh upload.py
