all: body-temperature heart-oxygen module pressure temperature-humidity

body-temperature:
	chmod -v +x body-temperature/main.py

heart-oxygen:
	chmod -v +x heart-oxygen/data_processing.py heart-oxygen/script.sh

module:
	chmod -v +x modules/*

pressure:
	chmod -v +x pressure/main.py

temperature-humidity:
	chmod -v +x temperature-humidity/main.py
